#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
    #nome do deployment
    name: lembretes-deployment
spec:
    #quantas copias
    replicas: 1
    #para especificar o rótulo
    selector:
        matchLabels:
            #rótulo, app não tem nada de especial, pode ser qq coisa
            #Deployment vai selecionar todo Pod que tiver esse rótulo
            app: lembretes
    #modelo que vai ser usado para construção dos Pods
    template:
        metadata:
            labels:
                #os Pods terão esse rótulo, assim,
                #serão selecionados por este deployment
                app: lembretes
        spec:
            containers:
                - name: lembretes
                  image: asbonato/lembretes:0.0.1